### ISSUE TITLE
Dishwasher support

### ISSUE THREAD

**Issue by martin131** [bilan/connectlife-api-connector#19]
Is this addon supporting also dishwashers? Or AC only?

**Comment by Bilan** [comment]
Addon exposes web API that can control every device from Connectlife app. Only AC is integrated with HA.

**Comment by martin131** [comment]
Right now I am considering buying a Gorenje dishwasher. So right now it is not possible, am I right? Any plans? :-)

**Comment by Bilan** [comment]
No plans for adding new devices. I have only AC device and based on it created this addon. Without testing on real device it's hard to add new one.

**Comment by Monacoslo** [comment]
> Addon exposes web API that can control every device from Connectlife app. Only AC is integrated with HA.

What do you need to integrate additional devices?

**Comment by martin131** [comment]
Yesterday my new Gorenje dishwasher arrived. Soon I can help you with integration too :)

**Comment by Bilan** [comment]
Sorry guys but no plans for adding new devices. I welcome pull requests :)

**Comment by Monacoslo** [comment]
> Sorry guys but no plans for adding new devices. I welcome pull requests :)

Can you please just explain how to add multiplle devices.

And what needs to be done to include additonal?

**Comment by Bilan** [comment]
Programming skills are required to add new device. You can suggest implementation of AC device.

**Comment by Monacoslo** [comment]
> Programming skills are required to add new device. You can suggest implementation of AC device.

I have 2 ACs with different code (109 and 104) and I wonder how could I add them both in configuration

**Comment by Bilan** [comment]
Both AC devices should be visible in HA. If not, create a new issue and paste your logs in it.

**Comment by Monacoslo** [comment]
I understand, but config is different. In what format should I put both codes?

**Comment by Bilan** [comment]
It should work without modifying the config. What the problem is?

**Comment by Monacoslo** [comment]
They have different modes available and are not shown properly.

**Comment by martin131** [comment]
Here is the `api/devices` response for my new dishwasher.
[gorenjeDishwasher.json](https://github.com/Bilan/connectlife-api-connector/files/14594247/gorenjeDishwasher.json)

**Comment by Monacoslo** [comment]
I can share configuration for my oven and washing machine if anyone would implement appliances

**Comment by Monacoslo** [comment]
Maybe someone can "merge" these 2 integrations, since HoN has already support for other device types

https://github.com/Andre0512/hon

**Comment by oyvindwe** [comment]
I have an Asko dishwasher, the device output is similar to yours: same `deviceFeatureCode`, `deviceFeatureName`, `deviceTypeCode` and `deviceTypeName`, and the `statusList` have all the same items.

I salute @bilan for figuring out authentication and the API, but I have started on a [custom integration](https://github.com/oyvindwe/connectlife-ha/), as I prefer to configure directly in HA instead of running a separate container in Docker and communicate over MQTT.

Currently the integration will only create sensor entities, and you can't control anything yet. I have set it up so I can monitor the status values over time.

**Comment by Monacoslo** [comment]
> I have an Asko dishwasher, the device output is similar to yours: same `deviceFeatureCode`, `deviceFeatureName`, `deviceTypeCode` and `deviceTypeName`, and the `statusList` have all the same items.
> 
> I salute @bilan for figuring out authentication and the API, but I have started on a [custom integration](https://github.com/oyvindwe/connectlife-ha/), as I prefer to configure directly in HA instead of running a separate container in Docker and communicate over MQTT.
> 
> Currently the integration will only create sensor entities, and you can't control anything yet. I have set it up so I can monitor the status values over time.

Very nice. Let me know if I can help testing. I have more ConnectLife devices

**Comment by gschot** [comment]
> I have an Asko dishwasher, the device output is similar to yours: same `deviceFeatureCode`, `deviceFeatureName`, `deviceTypeCode` and `deviceTypeName`, and the `statusList` have all the same items.
> 
> I salute @bilan for figuring out authentication and the API, but I have started on a [custom integration](https://github.com/oyvindwe/connectlife-ha/), as I prefer to configure directly in HA instead of running a separate container in Docker and communicate over MQTT.
> 
> Currently the integration will only create sensor entities, and you can't control anything yet. I have set it up so I can monitor the status values over time.

Will definitely try your custom integration, and also very interested. I just got an Atag dishwasher using ConnectLife. If you need info, let me know as well!

**Comment by oyvindwe** [comment]
>  I just got an Atag dishwasher using ConnectLife. If you need info, let me know as well!

Please share a JSON dump of your appliance if it differs from the other dishwashers

**Comment by gschot** [comment]
> > I just got an Atag dishwasher using ConnectLife. If you need info, let me know as well!
> 
> Please share a JSON dump of your appliance if it differs from the other dishwashers

Hmm... The entities listed for my Atag dishwasher look similar to those posted by @martin131 , only values differ. Probably no need to post then, I guess. I pulled the json by getting the /api/devices from the ha-connectlife-addon.

**Comment by oyvindwe** [comment]
Excellent. My dishwasher also has the same. No need to post the JSON dump.
