### ISSUE TITLE
Connection error: Unauthorized

### ISSUE THREAD

**Issue by tommasisimone** [Bilan/connectlife-api-connector#20]
I have 3 HiSense AC conected through ConnectLife and I installed the addon following the instructions.
I have Home Assistant OS and MQTT working correctly. 

When I start the component I have this error in the logs:
> E0309 00:19:43.401  discovery.py:43] Failed to login to Hisense server:
Status 401: 'Unauthorized'

This is my configuration:
`log_level: INFO
mqtt_host: 192.168.1.9
mqtt_port: 1883
mqtt_user: mymqttuser
mqtt_pass: mymqttpass
port: 8888
app:
  - username: myeamil
    password: mypassword
    code: hisense-eu`

The ConncetLife username and passwords are correct, I doublechecked it.
I also tried port 8000 instead of 8888
I tried all the codes from [this document](https://github.com/deiger/AirCon?tab=readme-ov-file#prerequisites) but no one worked. I'm living in Europe.

Any idea? I'm dreaming to have my AC in HA :)

**Comment by Bilan** [comment]
Hi, 
this log is weird:
"E0309 00:19:43.401 discovery.py:43] Failed to login to Hisense server:
Status 401: 'Unauthorized'"

Could you make a screenshot where you see it?

**Comment by Bilan** [comment]
I also do not understand reference to document under the link:
https://github.com/deiger/AirCon?tab=readme-ov-file#prerequisites

https://github.com/deiger/AirCon is different solution, different program. My add-on is not related with it.

**Comment by tommasisimone** [comment]
Hi Bilan, my bad, I installed "HiSense Air Conditioners" but I missed to install "Connectlife API proxy & MQTT Add-on". Now that I installed the second addon everything works great. Thank you very much for this addon, I was looking to integrate the AC with home assistant since so long.

Thank you!

**Comment by tommasisimone** [comment]
Closed
