### ISSUE TITLE
Getting error when trying to install in HA

### ISSUE THREAD

**Issue by tommi00** [bilan/connectlife-api-connector#33]
I'm receiving this error: 

The command '/bin/ash -o pipefail -c composer install --no-interaction --no-dev' returned a non-zero code: 2

What have I to do to solve?

**Comment by bilan** [comment]
Try version 2.1.11 please.

**Comment by tommi00** [comment]
> Try version 2.1.11 please.

Ok thank you, now I have been able to install it but cannot see devices on MQTT ha addon. 
The Mqtt parameters rightly configured: the mqtt receives some messages.
What have I to do to see te AC devices?

**Comment by bilan** [comment]
Paste more logs to see the context please.
