### ISSUE TITLE
Cant connect mqtt and Connectlife

### ISSUE THREAD

**Issue by Dayto0** [bilan/connectlife-api-connector#43]
Hi guys,what am i doing wrong? It seems that all the data I entered is correct, but mqtt does not detect connectlife. Please help me
(Using home assistant addon)
Logs
https://pastebin.com/QgqCkTx2

**Comment by bilan** [comment]
Hi,
try changing Connectlife App password.

**Comment by Dayto0** [comment]
> Hi, try changing Connectlife App password.

I changed the password and wrote new pass again. Nothing has changed

**Comment by bilan** [comment]
Could you paste addon logs after password change?

**Comment by Dayto0** [comment]
After changing password nothing has changed,but i reboot the Home assistant, and now everything is working. Thanks a lot

**Comment by Dayto0** [comment]
Besides temperature, are there other functions? (I really need the turbo and eco buttons)
