### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ghosty2004** [bilan/connectlife-api-connector#45]
Hi!

When I try to change my SPLIT AC device property value (e.g: `t_temp` to `24`) I receive an internal server error.

```
   WARN  production.INFO: ConnectLife: updating device. {"puid":"[censored]","properties":{"t_temp":"24"}} .  

  2024-06-26 17:11:36 .................................................................................................................... ~ 1s

   WARN  production.ERROR: Server error: `POST https://connectlife.bapi.ovh/appliances` resulted in a `500 Internal Server Error` response:  

   WARN  {.  

   WARN  "message": "Server Error".  

   WARN  }.  

   WARN  (GuzzleHttp\\Exception\\ServerException(code: 500): Server error: `POST https://connectlife.bapi.ovh/appliances` resulted in a `500 Internal Server Error` response:  

```

**Comment by chowhi123** [comment]
[2024-06-26 20:14:36] production.INFO: Updating HA device state ["pu000088650051000200030003000000887ddb7db1b"] 
Server error: `GET https://connectlife.bapi.ovh/appliances` resulted in a `500 Internal Server Error` response:
{
    "message": "Server Error"
}
I am sometimes getting this error too, but it might be just rate limited

**Comment by ghosty2004** [comment]
> [2024-06-26 20:14:36] production.INFO: Updating HA device state ["pu000088650051000200030003000000887ddb7db1b"] 
> 
> Server error: `GET https://connectlife.bapi.ovh/appliances` resulted in a `500 Internal Server Error` response:
> 
> {
> 
>     "message": "Server Error"
> 
> }
> 
> I am sometimes getting this error too, but it might be just rate limited

I don't think that this is rate limit... Every time I send an action to change a property I encounter the same issue.
