### ISSUE TITLE
homeassistant 24.9

### ISSUE THREAD

**Issue by dartfrogdk** [bilan/connectlife-api-connector#56]
after upgrading to newest homeassistant 24.9 i cant control the Heatpump but i can read the values and it shows as working but i cant change temperature or turn it of in Homeassistant

**Comment by gothrek** [comment]
same prob

**Comment by bilan** [comment]
I've upgraded my Homeassitant to 2024.09.1. The addon works with no issues. No problem with changing temperature. 

Try reinstalling the addon.
