### ISSUE TITLE
ConnectLife API Error on startup

### ISSUE THREAD

**Issue by hustiez** [bilan/connectlife-api-connector#7]
```log
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Connectlife API proxy / MQTT Add-on
 Integrates Connectlife AC devices with Home Assistant via MQTT and provides an HTTP API
-----------------------------------------------------------
 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.2.2
 Home Assistant Supervisor: 2024.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Config OK
MQTT creds: **************** / ***/ 1883 / no-ssl
2024-02-19 14:15:26,135 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-02-19 14:15:26,146 INFO supervisord started with pid 202
2024-02-19 14:15:27,157 INFO spawned: 'mqtt' with pid 203
2024-02-19 14:15:27,167 INFO spawned: 'www' with pid 204

   INFO  Server running on [http://0.0.0.0:8000].  

2024-02-19 14:15:28,156 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  Press Ctrl+C to stop the server

2024-02-19 14:15:29,158 INFO success: www entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

In RequestException.php line 113:
                                                                               
  Client error: `GET https://api.connectlife.io/api/v1/appliance` resulted in  
   a `404 Not Found` response                                                  
                                                                               

2024-02-19 14:15:30,076 WARN exited: mqtt (exit status 1; not expected)
2024-02-19 14:15:31,088 INFO spawned: 'mqtt' with pid 210
```

Did as instructed in README using Home Assistant integration method

**Comment by moskovskiy82** [comment]
Can you share the number of downloads for the repo? I have been in contact with Hisense for some time (everything is posted on HA community forums). Just as a try we can start a discussion once again on opening the API. I have read through the Haier case so @Bilan I will make that an anonymous plugin which was downloaded X times, starred 7 times e.tc. 150 unhappy customers telling their first circle what a brat is hisense is 1500 ppl awared. Further it's around 7500 ppl not wiiling to buy hisense )

**Comment by ekashuba** [comment]
> Unfortunately Connectlife removed API endpoints causing the application to stop working: https://api.connectlife.io/swagger/index.html

I think this same thing happened back in December but those "Appliance" API's reappeared after a few hours.  https://github.com/deiger/AirCon/issues/160#issuecomment-1853749612

Let's hope that history repeats itself and that those API's will be available again soon.

**Comment by delumerlino** [comment]
I have experienced a firmware update for the devices from the original app. Maybe they moved the services?

**Comment by delumerlino** [comment]
_Thank you for reaching out to ConnectLife supporting team! We apologize for the inconveniences, however we never offered a public API. Perhaps in the future but at this moment it can not be used.

 If you'll be experiencing any other issues related to CL app, please feel free to always reach out to us.


Kind regards_

What does it mean?

**Comment by moskovskiy82** [comment]
![image](https://github.com/Bilan/connectlife-api-connector/assets/15857592/3a9b00bc-6a89-440e-8da2-4dfa43df3fa9)

**Comment by moskovskiy82** [comment]
But as a question. Could it be an issue on the swagger side?
Not quite sure what is an API consumer 
https://swagger.io/tools/swaggerhub/pricing/

It might be that noticing traffic from different IP's with an API call they contacted HiSense to get some buck?

**Comment by moskovskiy82** [comment]
This is a strange answer I got back. Any ideas what is an abuse from HU?

Dear Andrey,
API is under the development but because of the community interest for API, we left '' unauthorized '' gate open. Unfortunately integration was abused from HU and we had to close it down until we will make it as it should be to protect users and the system. 
We appreciate your understanding and your input!

Kind regards
Neda Mijatović

**Comment by alexcroce** [comment]
> This is a strange answer I got back. Any ideas what is an abuse from HU?
> 
> Dear Andrey, API is under the development but because of the community interest for API, we left '' unauthorized '' gate open. Unfortunately integration was abused from HU and we had to close it down until we will make it as it should be to protect users and the system. We appreciate your understanding and your input!
> 
> Kind regards Neda Mijatović

Someone from hungary abused the api

**Comment by moskovskiy82** [comment]
@Bilan Maybe you can discuss with them to work out possible solutions? Any problem can be solved i believe )

**Comment by alexcroce** [comment]
> I hope so :) please note the ID of devices will change.

I can't Update in homeassistant, i see version 1.1.0

**Comment by ustix** [comment]
> > I hope so :) please note the ID of devices will change.
> 
> I can't Update in homeassistant, i see version 1.1.0

Same for me.

**Comment by Bolo92** [comment]
Home assistant -> settings -> addons -> up, right corner -> click checks for updates -> go to this addons and you will see update button.
After update it works for me only entity was changed.
@Bilan brillant work ;) thanks

**Comment by alexcroce** [comment]
`In AcDevice.php line 39:
                                           
  [ErrorException]                         
  Undefined array key "t_swing_direction"  
                                           

Exception trace:
  at /home/app/app/Services/AcDevice.php:39`

It doesn't work for me.

**Comment by alexcroce** [comment]
`
    \"cookieName\": \"gac_4_yhTWQmHFpZkQZDSV1uV-_A\",

    \"cookieValue\": \"st2.s.AtLt_dniGw.QhE5pKMm80uK3ihh5cixHDG-UBUQbBtEsP4aa7j3X4KGLpsF6805PAkEJ0AlLXnYZaum8wT9GXEbWqVw5ZXGJsOns5lfdb2O5mgGEoJJX56esbuetRdlqgqTqYlWtG66.sEzZJbVAR1PcLdpTJFLMIq3Ln11eKeHyXkcFmij3dJ6w0SUwW3bj5C-204sNp5j37rzsrCv0EQWafaTwcge2Xg.sc3\"

  }

}"] 
[2024-02-25 09:27:22] production.INFO: Response ["{

  \"callId\": \"b2034c1b6d70406dbe896173f1b9fb2e\",

  \"errorCode\": 0,

  \"apiVersion\": 2,

  \"statusCode\": 200,

  \"statusReason\": \"OK\",

  \"time\": \"2024-02-25T09:27:22.653Z\",

  \"id_token\": \"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyJ9.eyJpc3MiOiJodHRwczovL2ZpZG0uZ2lneWEuY29tL2p3dC80X3loVFdRbUhGcFprUVpEU1YxdVYtX0EvIiwiYXBpS2V5IjoiNF95aFRXUW1IRnBaa1FaRFNWMXVWLV9BIiwiaWF0IjoxNzA4ODUzMjQyLCJleHAiOjE3MDg4NTM1NDIsInJpc2tTY29yZSI6MC40Nywic3ViIjoiYmJkZTJhYTE0N2I0NDgxZGJkZWRiZGUwZDUyZGUzNmYifQ.NhCEHOv1urcVtiZHDyVOAqoqCrSJ_Y27yLbQMJ2dkRqfw5cuht9NO_WEI12ufAxs5Eabb7CzH8uE620iCvUZ0WvlhsmQwkU3vzVYChFi3DyXXRf7kyqCp7LbnCC95k8G0Jw93BjDMeBZkNkpvIxvTMQihLvv0jzQ2JSmFqySS2KF3WbViYQiKPd1f0mp6YtujL8l7e6444RsdsHWdgvqEEA8fmFRFFNXS_a5ukmw0LlNkaZi_K9ajPkkJjJIdASxm31016GSo5TPn4TbLlmds5A5rAoviZvxlD4yycDISC5ZUIIcmXjEF1pKXA2dYcJQhnYwTLsTGf_uP9jg0_d6nQ\"

}"] 
[2024-02-25 09:27:23] production.INFO: Response ["{\"resultCode\":0,\"code\":\"e114512d1f4a6b4a3481fff37e5ce8ba\",\"redirect_uri\":\"https://api.connectlife.io/swagger/oauth2-redirect.html\",\"state\":null}"] 
[2024-02-25 09:27:23] production.INFO: Response ["{\"resultCode\":0,\"access_token\":\"pa3u47xnRnfcy7qqsjRweLt3ACThrT2VDNWZOfBKMV_OojBXuPkTqrR3trCAKOnpJoXX5zI_06ugKwvnJQ_yAmaxMIIA09CvodQJE0nW207KoDm8HZB_zhL7KAOFbRooWLAJn-RblJ7kVgL9h0LWwqtmBQy8SvljRaDZZU2kYTPpKIclHuLn_lKxf1iVbBZUONHAd459DkeNGXKQCNRcL9jbbubCp21Ym3HzhvuXSf7cd6m8aHwqF6IjTYvCPIuLD5FEtqQFyk51eRL-jNh32OP-B5cxQ8q2-BD9UiGIXqU2UmdbATB2-R-4yDPgFDnnrm23slKNnARekBt_yVP2z64DU8KFqnJbFb0rUyQi9qBKKr7tAGHM_CZaW3P0C5uGRGC0uQzzBLV_8THjjo4DZwLKg\",\"token_type\":\"Bearer\",\"expires_in\":1440,\"scope\":\"\",\"refresh_token\":\"pr3u47xnRnfcy7qqsjRweLt3ACThrT2VDNWZOfBKMV_OojBXuPkTqrR3trCAKOnpJoXX5zI_06ugKwvnJQ_yAmaxMIIA09CvodQJE0nW207KoDm8HZB_zhL7KAOFbRooWLAJn-RblJ7kVgL9h0LWwqtmBQy8SvljRaDZZU2kYTPpKIclHuLn_lKxf1iVbBZUONHAd459DkeNGXKQCNRcL9jbbubCp21Ym3HzhvuXSf7cd6m8aHwqF6IjTYvCPIuLD5FEtqQFyk51eRL-jNh32OP-La-bmjVht02Vb9UdV_QOpDuk4LmuweE6EV6Am-sxTB6TDJQTDXJdQ3JUKas70zv2uYK9U3putfl2FsT71LQHHc1PT4iH5Kan2-YKRPWCv_1qdIlocgII1NyRQb-7O4Nmg\"}"] 
[2024-02-25 09:27:38] production.INFO: Response ["[{\"wifiId\":\"8650051000200030003000001023dca9df07\",\"deviceId\":\"8650051000200030003000001023dca9df07\",\"puid\":\"pu000098650051000200030003000001023dca9df07\",\"deviceNickName\":\"Split Cucina\",\"deviceFeatureCode\":\"104\",\"deviceFeatureName\":\"104\\u51b7\\u6696\\u8282\\u80fd\\u65e0\\u529f\\u7387\",\"deviceTypeCode\":\"009\",\"deviceTypeName\":\"\",\"bindTime\":1704741589874,\"role\":1,\"roomId\":3540181,\"roomName\":\"Cucina\",\"statusList\":{\"t_work_mode\":\"1\",\"t_power\":\"0\",\"t_temp\":\"22\",\"t_temp_type\":\"0\",\"t_fan_speed\":\"0\",\"t_fan_speed_s\":\"0\",\"t_up_down\":\"0\",\"t_sleep\":\"0\",\"t_eco\":\"0\",\"t_fan_mute\":\"0\",\"t_super\":\"0\",\"f_temp_in\":\"19\",\"f_e_push\":\"0\",\"f_e_intemp\":\"0\",\"f_e_incoiltemp\":\"0\",\"f_e_inhumidity\":\"0\",\"f_e_infanmotor\":\"0\",\"f_e_arkgrille\":\"0\",\"f_e_invzero\":\"0\",\"f_e_incom\":\"0\",\"f_e_indisplay\":\"0\",\"f_e_inkeys\":\"0\",\"f_e_inwifi\":\"0\",\"f_e_inele\":\"0\",\"f_e_ineeprom\":\"0\",\"f_e_outeeprom\":\"0\",\"f_e_outcoiltemp\":\"0\",\"f_e_outgastemp\":\"0\",\"f_e_outtemp\":\"0\"},\"useTime\":0,\"offlineState\":1,\"seq\":0,\"createTime\":0},{\"wifiId\":\"8650051000200030003000001023dca9f952\",\"deviceId\":\"8650051000200030003000001023dca9f952\",\"puid\":\"pu000098650051000200030003000001023dca9f952\",\"deviceNickName\":\"Split Sala\",\"deviceFeatureCode\":\"104\",\"deviceFeatureName\":\"104\\u51b7\\u6696\\u8282\\u80fd\\u65e0\\u529f\\u7387\",\"deviceTypeCode\":\"009\",\"deviceTypeName\":\"\",\"bindTime\":1704741304842,\"role\":1,\"roomId\":3540167,\"roomName\":\"Sala\",\"statusList\":{\"t_work_mode\":\"1\",\"t_power\":\"0\",\"t_temp\":\"22\",\"t_temp_type\":\"0\",\"t_fan_speed\":\"0\",\"t_fan_speed_s\":\"0\",\"t_up_down\":\"0\",\"t_sleep\":\"0\",\"t_eco\":\"0\",\"t_fan_mute\":\"0\",\"t_super\":\"0\",\"f_temp_in\":\"20\",\"f_e_push\":\"0\",\"f_e_intemp\":\"0\",\"f_e_incoiltemp\":\"0\",\"f_e_inhumidity\":\"0\",\"f_e_infanmotor\":\"0\",\"f_e_arkgrille\":\"0\",\"f_e_invzero\":\"0\",\"f_e_incom\":\"0\",\"f_e_indisplay\":\"0\",\"f_e_inkeys\":\"0\",\"f_e_inwifi\":\"0\",\"f_e_inele\":\"0\",\"f_e_ineeprom\":\"0\",\"f_e_outeeprom\":\"0\",\"f_e_outcoiltemp\":\"0\",\"f_e_outgastemp\":\"0\",\"f_e_outtemp\":\"0\"},\"useTime\":0,\"offlineState\":1,\"seq\":0,\"createTime\":0}]"] 
[2024-02-25 09:27:38] production.ERROR: Undefined array key "t_swing_direction" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"t_swing_direction\" at /home/app/app/Services/AcDevice.php:39)
[stacktrace]
#0 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/app/app/Services/AcDevice.php(39): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/app/app/Services/ConnectlifeApiService.php(140): App\\Services\\AcDevice->__construct()
#3 /home/app/app/Services/MqttService.php(18): App\\Services\\ConnectlifeApiService->getOnlineAcDevices()
#4 [internal function]: App\\Services\\MqttService->__construct()
#5 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(952): ReflectionClass->newInstanceArgs()
#6 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#7 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()
#8 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#9 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()
#10 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\\Foundation\\Application->make()
#11 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\\Container\\BoundMethod::addDependencyForCallParameter()
#12 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Container\\BoundMethod::getMethodDependencies()
#13 /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#17 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#18 /home/app/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#19 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#20 /home/app/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#21 /home/app/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /home/app/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#23 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#24 /home/app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"} 

In AcDevice.php line 39:
                                           
  [ErrorException]                         
  Undefined array key "t_swing_direction"  
                                           

Exception trace:
  at /home/app/app/Services/AcDevice.php:39
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:255
 Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}() at /home/app/app/Services/AcDevice.php:39
 App\Services\AcDevice->__construct() at /home/app/app/Services/ConnectlifeApiService.php:140
 App\Services\ConnectlifeApiService->getOnlineAcDevices() at /home/app/app/Services/MqttService.php:18
 App\Services\MqttService->__construct() at n/a:n/a
 ReflectionClass->newInstanceArgs() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:952
 Illuminate\Container\Container->build() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
 Illuminate\Container\Container->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:957
 Illuminate\Foundation\Application->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
 Illuminate\Container\Container->make() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942
 Illuminate\Foundation\Application->make() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:181
 Illuminate\Container\BoundMethod::addDependencyForCallParameter() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:124
 Illuminate\Container\BoundMethod::getMethodDependencies() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
 Illuminate\Container\Util::unwrapIfClosure() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
 Illuminate\Container\BoundMethod::call() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:662
 Illuminate\Container\Container->call() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:211
 Illuminate\Console\Command->execute() at /home/app/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->run() at /home/app/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /home/app/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /home/app/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
 Illuminate\Foundation\Console\Kernel->handle() at /home/app/artisan:35

s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

Thanks

**Comment by alexcroce** [comment]
> @alexcroce I deleted your logs because of access token was there. I will try to fix your problem in v2.1

Thanks so much!

**Comment by alexcroce** [comment]
> @alexcroce v2.1.0 is out now.

It Works! Thanks. If you need something to develope swing settings please tell me

**Comment by alexcroce** [comment]
> You will need to click on each swing option in the application and save the API response.

How can i save the Api responses?

**Comment by delumerlino** [comment]
How may I know my deviceFeatureCodes?

**Comment by delumerlino** [comment]
Oh nice. I have 009, it supports only up/down swing, should I remove t_swing_direction?

**Comment by moskovskiy82** [comment]
@Bilan how did you make it work? Did HiSense help
